# Generated by Django 5.2.1 on 2025-05-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='songs',
            field=models.ManyToManyField(to='main.song'),
        ),
    ]
