# Generated by Django 5.2.1 on 2025-06-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_song_schedule_schedule_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.CharField(max_length=4),
        ),
    ]
