# Generated by Django 5.2.1 on 2025-06-11 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_schedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='name',
        ),
    ]
