# Generated by Django 5.2.1 on 2025-11-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_song_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='last_scheduled',
            field=models.DateField(blank=True, null=True),
        ),
    ]
