# Generated by Django 5.2.1 on 2025-11-20 19:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0007_song_last_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=150)),
                ('date_of_action', models.DateField(default=datetime.datetime(2025, 11, 20, 19, 56, 58, 333104, tzinfo=datetime.timezone.utc))),
                ('obj_id', models.PositiveIntegerField()),
                ('obj_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
        ),
    ]
