# Generated by Django 5.2.1 on 2025-11-24 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_song_name_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='obj_content_type',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='obj_id',
        ),
        migrations.AddField(
            model_name='logs',
            name='obj_name',
            field=models.CharField(default='No Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='logs',
            name='date_of_action',
            field=models.DateField(default=datetime.datetime(2025, 11, 24, 19, 13, 1, 372176, tzinfo=datetime.timezone.utc)),
        ),
    ]
