# Generated by Django 5.2.1 on 2025-12-31 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_logs_obj_content_type_remove_logs_obj_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='last_scheduled',
            new_name='scheduled',
        ),
        migrations.AlterField(
            model_name='logs',
            name='date_of_action',
            field=models.DateField(default=datetime.datetime(2025, 12, 31, 20, 0, 48, 13961, tzinfo=datetime.timezone.utc)),
        ),
    ]
