# Generated by Django 5.2.1 on 2025-12-31 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_last_scheduled_song_scheduled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='last_scheduled',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='date_of_action',
            field=models.DateField(default=datetime.datetime(2025, 12, 31, 20, 1, 6, 222721, tzinfo=datetime.timezone.utc)),
        ),
    ]
