# Generated by Django 5.2.1 on 2026-04-07 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_song_last_scheduled_alter_logs_date_of_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='date_of_action',
            field=models.DateField(default=datetime.datetime(2026, 4, 7, 19, 51, 55, 375851, tzinfo=datetime.timezone.utc)),
        ),
    ]
